name: flexi_formatter
version: 2.0.0
description: A flexible and customizable Dart/Flutter library for formatting numbers, dates, and other data types.
homepage: https://github.com/FlexiKline
repository: https://github.com/FlexiKline/flexi_formatter

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  decimal: ^3.2.4
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
